mod backend;
mod cell_surface;
mod clipboard_image;
pub mod glyphs;
mod layout;
mod rail_bridge;
mod scene;
mod selection;
mod sidebar;
mod sidecar_reducer;
mod status;
mod terminal_manager;
mod terminal_view;
mod theme;
pub mod tui;
mod workspace;
